### ISSUE TITLE
SSL error on new MacBook/OS X 10.12.5/Python 2.7.10

### ISSUE THREAD

**Issue by nikhaldi** [descarteslabs/descarteslabs-python#103]
On a brand new MacBook with OS X 10.12.5/Python 2.7.10 I got SSL issues when trying to authenticate:

```
$ descarteslabs auth login
Follow this link to login https://iam.descarteslabs.com/auth/login?refresh_token=true&destination=/auth/refresh_token
...then come back here and paste the generated token: <omitted>
Traceback (most recent call last):
  File "/Users/nik/Projects/descarteslabs-python/env/bin/descarteslabs", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/scripts/descarteslabs", line 19, in <module>
    handle(parser.parse_args())
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/scripts/parser/__init__.py", line 81, in handle
    auth_handler(args)
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/scripts/parser/auth.py", line 61, in auth_handler
    keys = dl.metadata.keys()
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/services/metadata.py", line 285, in keys
    params=params, limit=limit, offset=offset, bbox=bbox)
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/services/metadata.py", line 231, in search
    r = self.session.post('%s/search' % self.url, json=kwargs, timeout=self.TIMEOUT)
  File "/Users/nik/Projects/descarteslabs-python/env/lib/python2.7/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/nik/Projects/descarteslabs-python/descarteslabs/services/service.py", line 28, in request
    resp = super(WrappedSession, self).request(method, url, **kwargs)
  File "/Users/nik/Projects/descarteslabs-python/env/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/nik/Projects/descarteslabs-python/env/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/nik/Projects/descarteslabs-python/env/lib/python2.7/site-packages/requests/adapters.py", line 512, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)
```

This is on Python 2.7.10, so requests[security] was not selected as a dependency. Once I forced installation of requests[security] in the virtualenv, it worked. Not sure, but it may be a good idea to always select request[security] as dep on OS X regardless of Python version.

**Comment by nikhaldi** [comment]
Should be fixed by https://github.com/descarteslabs/metadata/pull/142
