### ISSUE TITLE
Platform sometimes times out when retrieving data

### ISSUE THREAD

**Issue by amanda759** [descarteslabs/descarteslabs-python#121]
When I call `dl.metadata.search()`, it's hit or miss in terms of whether or not the data are actually returned. Sometimes the search is successful, and oftentimes--for the same search--the platform times out.

For example, in the following code (which is similar to the provided example in the documentation), I'm looking for up to 200 Landsat images over Brazil from Jan 2016 - Jan 2017.

```python
from pprint import pprint
import descarteslabs as dl
import itertools

# Find matches for Brazil
matches = dl.places.find('brazil')
pprint(matches)

# Make it the area of interest
aoi = matches[0]

# Search for available imagery
sources = dl.metadata.sources()
groups = {}
for group, items in itertools.groupby(sources, key=lambda v: v['const_id']):
    groups[group] = list(items)
pprint(groups)

# Search over time/space/satellite 
swathlim = 200
date_start = '2016-01-01'
date_end = '2017-01-01'
const_id = ['L5','L7','L8','L8SR']
feature_collection = dl.metadata.search(const_id=const_id,start_time=date_start,
	end_time=date_end,limit=swathlim,place=aoi['slug'])
print len(feature_collection['features'])
```

When I run it, the "matches" for Brazil print, and so do the constellation IDs. But when it comes to `feature_collection = dl.metadata.search()`, the system often times out. When I run the above code, I sometimes get the following:

```
[{'bbox': [-73.99045, -33.752081, -28.835944, 5.271841],
  'id': 85633009,
  'name': 'Brazil',
  'path': 'continent:south-america_country:brazil',
  'placetype': 'country',
  'slug': 'south-america_brazil'}]
{'CDL': [{'const_id': 'CDL', 'sat_id': 'CDL', 'value': 140}],
 'L5': [{'const_id': 'L5', 'sat_id': 'LANDSAT_4', 'value': 119}],
 'L7': [{'const_id': 'L7', 'sat_id': 'LANDSAT_7', 'value': 112}],
 'L8': [{'const_id': 'L8', 'sat_id': 'LANDSAT_8', 'value': 89}],
 'L8SR': [{'const_id': 'L8SR', 'sat_id': 'L8SR', 'value': 142}],
 'NAIP': [{'const_id': 'NAIP', 'sat_id': 'NAIP', 'value': 121}],
 'S1A': [{'const_id': 'S1A', 'sat_id': 'SENTINEL-1A', 'value': 108}],
 'S1B': [{'const_id': 'S1B', 'sat_id': 'SENTINEL-1B', 'value': 107}],
 'S2A': [{'const_id': 'S2A', 'sat_id': 'S2A', 'value': 111}],
 'S3A': [{'const_id': 'S3A', 'sat_id': 'S3A', 'value': 110}],
 'modis09': [{'const_id': 'modis09', 'sat_id': 'Terra', 'value': 3},
             {'const_id': 'modis09', 'sat_id': 'Aqua', 'value': 4}],
 'srtm': [{'const_id': 'srtm', 'sat_id': 'srtm', 'value': 120}]}
Traceback (most recent call last):
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/ssl.py", line 1002, in recv_into
    return self.read(nbytes, buffer)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/ssl.py", line 865, in read
    return self._sslobj.read(len, buffer)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/ssl.py", line 625, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 388, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/adapters.py", line 438, in send
    timeout=timeout
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 678, in urlopen
    **response_kw)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Max retries exceeded with url: /runcible/v1/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Read timed out. (read timeout=120)",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dl_issues_script.py", line 55, in <module>
    end_time=date_end,limit=swathlim,place=aoi['slug'])
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/descarteslabs/services/metadata.py", line 231, in search
    r = self.session.post('%s/search' % self.url, json=kwargs, timeout=self.TIMEOUT)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/sessions.py", line 565, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/descarteslabs/services/service.py", line 28, in request
    resp = super(WrappedSession, self).request(method, url, **kwargs)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/Users/AZiemann/anaconda/envs/descartes/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Max retries exceeded with url: /runcible/v1/search (Caused by ReadTimeoutError("HTTPSConnectionPool(host='platform-services.descarteslabs.com', port=443): Read timed out. (read timeout=120)",))
```

I've tried varying both the data range (e.g., 2010-2017, 2016-2017, one month in 2017), as well as the `limit` variable for the number of images/swaths (e.g., 10, 200, 1000), and I can't find any consistency in terms of if there are certain parameter choices (like a large date range or large `limit` of images) that causes the code to break. Sometimes they work, and sometimes they don't. I've double checked the proxy on our end, and it's working correctly, so no issues there.

**Comment by samskillman** [comment]
Hi @amanda759 , thanks for the feedback! This should be considerably better on the master branch of this repository. Make sure you check out the changelog in the current readme though because there are a few changes. Specifically that groupby won't be needed as we've replaced it with the concept of a "product".

**Comment by amanda759** [comment]
Thanks Sam! I just successfully installed master. I'm about to head home but I'll play around with it this week and will report back asap.
