### ISSUE TITLE
Authentication issue

### ISSUE THREAD

**Issue by proflage** [descarteslabs/descarteslabs-python#214]
I create a Docker image and tried to authenticate at DL but I got the following error:

```
...
Step 20/23 : RUN descarteslabs auth env
 ---> Running in a17beef2192b
Traceback (most recent call last):
  File "/usr/local/bin/descarteslabs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/descarteslabs/client/scripts/__main__.py", line 20, in main
    handle(parser.parse_args())
  File "/usr/local/lib/python3.6/site-packages/descarteslabs/client/scripts/cli.py", line 81, in handle
    auth_handler(args)
  File "/usr/local/lib/python3.6/site-packages/descarteslabs/client/auth/cli.py", line 76, in auth_handler
    auth.token
  File "/usr/local/lib/python3.6/site-packages/descarteslabs/client/auth/auth.py", line 122, in token
    self._get_token()
  File "/usr/local/lib/python3.6/site-packages/descarteslabs/client/auth/auth.py", line 153, in _get_token
    raise AuthError("Could not find CLIENT_ID")
descarteslabs.client.exceptions.AuthError: Could not find CLIENT_ID
The command '/bin/sh -c descarteslabs auth env' returned a non-zero code: 1
...
```

**Docker image** is here https://hub.docker.com/r/lage/descarteslabs/ and tag is `auth-issue`.

When I ran `docker build -t dl:dev .` the Dockerfile had my [Jason Web Token](https://iam.descarteslabs.com/auth/credentials) instead of `MY_JASON_WEB_TOKEN`.

I also interactively accessed a container and set up these environment vars and ran `descarteslabs auth env` from there but I got the same error:

```bash
$ export CLIENT_ID=[my email address]
$ export CLIENT_SECRET=[email password]
```

**Comment by hrfuller** [comment]
Hi Andre, your `CLIENT_ID` and `CLIENT_SECRET` are special offline credentials that you have to create through [IAM](https://iam.descarteslabs.com/auth/credentials). Click on the Generate button under Offline Access to do so.

**Comment by proflage** [comment]
it worked, thanks!

```bash
$ docker run dl:debug descarteslabs auth env
CLIENT_ID=ZOBAi4UROl5gKZIpxxlwOEfx8KpqXf2c
CLIENT_SECRET=vv8afPwohjxq6ewjHRiKcdslhdthKv7tLwU0VcW9uPARk
alage@Andres-MacBook-Pro-2:~$ 
```
