### ISSUE TITLE
URGENT: descarteslabs==1.2.0 workflows reflecting a breaking change with latest release of 1.4.0

### ISSUE THREAD

**Issue by jens2121** [descarteslabs/descarteslabs-python#237]
## Expected Behavior
 Existing workflows created/published in version 1.2.0 will be compatible with latest releases. This is expected unless deprecated in following descarteslabs versions, but deprecated warnings would be expected.

## Actual Behavior
We have multiple application deployments pinned to version 1.2.0, however since the latest deployment of 1.4.0 the publishing of our workflow layers fails with a 501 error! See the error below. Program was working on Thursday, and its started failing yesterday

```
Traceback (most recent call last): 
  File ".\dl_download_v5.py", line 291, in <module> 
    read_grid.apply(run_grid_block, axis=1) 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\pandas\core\frame.py", line 6878, in apply 
    return op.get_result() 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\pandas\core\apply.py", line 186, in get_result 
    return self.apply_standard() 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\pandas\core\apply.py", line 313, in apply_standard 
    results, res_index = self.apply_series_generator() 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\pandas\core\apply.py", line 341, in apply_series_generator 
    results[i] = self.f(v) 
  File ".\dl_download_v5.py", line 282, in run_grid_block 
    output_directory=output_directory) 
  File ".\dl_download_v5.py", line 174, in export_s1_data 
    composite_type='median' 
  File ".\dl_download_v5.py", line 67, in get_radar_workflow_id 
    workflow = wf.publish(workflow_layer) 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\descarteslabs\workflows\__init__.py", line 165, in publish 
    return _publish(obj, name, description, client) 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\descarteslabs\workflows\models\toplevel.py", line 101, in publish 
    workflow.save() 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\descarteslabs\workflows\models\workflow.py", line 199, in save 
    timeout=self._client.DEFAULT_TIMEOUT, 
  File "C:\Users\jens.hiestermann\.conda\envs\descartes-labs-workflows\lib\site-packages\descarteslabs\workflows\client\client.py", line 53, in wrapper 
    raise from_grpc_error(e) from None 
descarteslabs.workflows.client.exceptions.MethodNotImplemented: 501
``` 
## Severity
HIGHLY URGENT
![image](https://user-images.githubusercontent.com/23120545/92449781-d819c500-f1ba-11ea-8d22-1fe61b6b6116.png)

**Comment by stephaniegott** [comment]
Thanks for reporting! The `descarteslabs==1.2.0` client has been deprecated. We support only the two latest versions (currently `1.3.0` and `1.4.0`). Additionally there were significant changes to the `Workflow` sharing functionality in version `1.4.0`. We will update the Changelog to reflect these breaking changes. In the meantime, updating to `descarteslabs==1.3.0` will fix any exceptions you may be getting.

**Comment by jens2121** [comment]
Thanks for the response Stephanie, will update accordingly.
